platform :ios, '9.3'

target 'CordingTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CordingTest
  pod 'Alamofire'
  pod 'Kingfisher'
  pod 'SwiftyJSON'
  pod 'RealmSwift'
  pod 'SwiftyUserDefaults'
  pod 'SVProgressHUD'
  
  target 'CordingTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CordingTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
